"""Regression tests for Conditional-Judgment (type 7) and Variable-Assignment (type 10)
flow-model reading — Task 5.

Fixture: tests/fixtures/conditional_varassign.json
  Generated by wiz-builder (committed); contains one component named "Flow" with:
    - a talk entry node  (type 1)
    - a conditional node (type 7) — variable PAYMENT_STATUS, branches Paid/Unpaid/Default
    - two assign nodes   (type 10) — variable SALUTATION
    - an exit node       (type 2)

These tests lock the reader behaviour so that future refactors of flowmodel.py or
flow_constants.py cannot silently break type-7 / type-10 parsing.

No production change was needed: NODE_TYPE_MAP already maps 7→"conditional" and
10→"variable_assignment"; _build_branches already emits kind="condition"/"default"
for type-7 and kind="next" for type-10.
"""
from __future__ import annotations

import json
from pathlib import Path

import pytest
from wizcheck.flowmodel import build_components

# ---------------------------------------------------------------------------
# Fixture path
# ---------------------------------------------------------------------------
# File: .claude/skills/wiz-checker/tests/test_flowmodel_conditional.py
#   parents[0] = tests/
#   parents[1] = wiz-checker/
#   parents[2] = skills/
#   parents[3] = .claude/
#   parents[4] = repo-root/
_FIXTURE = (
    Path(__file__).resolve().parent
    / "fixtures"
    / "conditional_varassign.json"
)


@pytest.fixture(scope="module")
def flow_comp():
    """Return the 'Flow' FlowComponent built from the builder-generated fixture."""
    if not _FIXTURE.exists():
        pytest.skip(f"Fixture not found: {_FIXTURE}")
    data = json.loads(_FIXTURE.read_text("utf-8"))
    comps = build_components(data)
    comp = next((c for c in comps if c.name == "Flow"), None)
    assert comp is not None, "Component 'Flow' not found in fixture"
    return comp


# ---------------------------------------------------------------------------
# Helpers
# ---------------------------------------------------------------------------

def _find_node_by_type(comp, node_type: str):
    """Return the first node with the given node_type, or None."""
    return next((n for n in comp.nodes.values() if n.node_type == node_type), None)


# ---------------------------------------------------------------------------
# Test 1: Conditional node emits condition + default branches
# ---------------------------------------------------------------------------

class TestConditionalNodeBranches:
    def test_conditional_emits_condition_and_default_branches(self, flow_comp):
        """type-7 node must emit at least one 'condition' branch and a 'default' branch."""
        node = _find_node_by_type(flow_comp, "conditional")
        assert node is not None, "No 'conditional' node found in component 'Flow'"

        kinds = [b.kind for b in node.branches]
        assert "condition" in kinds, (
            f"Expected a 'condition' branch; got kinds: {kinds}"
        )
        default_branches = [b for b in node.branches if b.kind == "default"]
        assert len(default_branches) >= 1, (
            f"Expected a 'default' branch; got kinds: {kinds}"
        )
        assert default_branches[0].label == "Default", (
            f"Default branch label should be 'Default', got: {default_branches[0].label!r}"
        )

    def test_conditional_references_payment_status(self, flow_comp):
        """type-7 node must list PAYMENT_STATUS in referenced_vars."""
        node = _find_node_by_type(flow_comp, "conditional")
        assert node is not None
        assert "PAYMENT_STATUS" in node.referenced_vars, (
            f"Expected 'PAYMENT_STATUS' in referenced_vars; got: {node.referenced_vars}"
        )


# ---------------------------------------------------------------------------
# Test 2: Variable-assignment node emits 'next' branch + writes SALUTATION
# ---------------------------------------------------------------------------

class TestVariableAssignmentNodeBranches:
    def test_assign_emits_next_branch_and_writes_var(self, flow_comp):
        """type-10 node must have a branch with kind='next' and reference SALUTATION."""
        node = _find_node_by_type(flow_comp, "variable_assignment")
        assert node is not None, "No 'variable_assignment' node found in component 'Flow'"

        next_branches = [b for b in node.branches if b.kind == "next"]
        assert len(next_branches) >= 1, (
            f"Expected a 'next' branch on variable_assignment node; "
            f"got kinds: {[b.kind for b in node.branches]}"
        )
        assert "SALUTATION" in node.referenced_vars, (
            f"Expected 'SALUTATION' in referenced_vars; got: {node.referenced_vars}"
        )


# ---------------------------------------------------------------------------
# Test 3: Node-type mapping is correct — no 'unknown' for types 7 and 10
# ---------------------------------------------------------------------------

class TestNodeTypeMapping:
    def test_node_types_mapped(self, flow_comp):
        """The 'Flow' component must include 'conditional' and 'variable_assignment',
        and must NOT include 'unknown'."""
        all_types = {n.node_type for n in flow_comp.nodes.values()}

        assert "conditional" in all_types, (
            f"'conditional' missing from node types: {all_types}"
        )
        assert "variable_assignment" in all_types, (
            f"'variable_assignment' missing from node types: {all_types}"
        )
        assert "unknown" not in all_types, (
            f"'unknown' node type present — type mapping is incomplete: {all_types}"
        )
